### ISSUE TITLE
Heroku本番環境でログイン&新規ユーザー作成ができなくなった

### ISSUE THREAD

**Issue by shuhei-T** [shuhei-T/reptiles_log#105]
本番環境でログインしようとすると、このようなエラーが出てしまいました。
新規ユーザー作成しようとすると、同様のエラーが出ます。

[![Image from Gyazo](https://i.gyazo.com/1cceeb893e36acee4c049a1bcb883155.png)](https://gyazo.com/1cceeb893e36acee4c049a1bcb883155)

**Comment by takyyk** [comment]
一旦ログイン時の処理を行うコントローラに```protect_from_forgery```  または```skip_before_action :verify_authenticity_token```をつけてみるとどうなりますか？

**Comment by shuhei-T** [comment]
@takyyk 
コメントありがとうございます！
7162ffe で指定された箇所に追記してHerokuにデプロイしました。

ログインを試してみると、ログインできました。

次に、ゲストユーザーを作成しようとしたら、再びエラーが出ました。
[![Image from Gyazo](https://i.gyazo.com/5c5c9f9448a9ec84528ec26993ac874e.png)](https://gyazo.com/5c5c9f9448a9ec84528ec26993ac874e)

こちらがHerokuログの結果になります
```ruby
2022-03-06T06:17:10.950436+00:00 app[web.1]: I, [2022-03-06T06:17:10.950369 #4]  INFO -- : [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] Started POST "/users" for 172.70.233.95 at 2022-03-06 06:17:10 +0000
2022-03-06T06:17:10.951172+00:00 app[web.1]: I, [2022-03-06T06:17:10.951123 #4]  INFO -- : [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] Processing by UsersController#create as HTML
2022-03-06T06:17:10.955694+00:00 app[web.1]: I, [2022-03-06T06:17:10.955592 #4]  INFO -- : [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76]   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"name"=>"ゲスト", "email"=>"guest@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"アカウントを作成する"}
2022-03-06T06:17:10.955976+00:00 app[web.1]: W, [2022-03-06T06:17:10.955922 #4]  WARN -- : [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] HTTP Origin header (https://www.reptileslog.com) didn't match request.base_url (http://www.reptileslog.com)
2022-03-06T06:17:10.957003+00:00 app[web.1]: I, [2022-03-06T06:17:10.956948 #4]  INFO -- : [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Allocations: 213)
2022-03-06T06:17:10.958167+00:00 app[web.1]: F, [2022-03-06T06:17:10.958108 #4] FATAL -- : [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76]
2022-03-06T06:17:10.958168+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
2022-03-06T06:17:10.958170+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76]
2022-03-06T06:17:10.958171+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
2022-03-06T06:17:10.958171+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
2022-03-06T06:17:10.958172+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] sorcery (0.16.2) lib/sorcery/controller.rb:125:in `handle_unverified_request'
2022-03-06T06:17:10.958172+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
2022-03-06T06:17:10.958172+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/callbacks.rb:427:in `block in make_lambda'
2022-03-06T06:17:10.958173+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
2022-03-06T06:17:10.958173+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
2022-03-06T06:17:10.958174+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/callbacks.rb:199:in `block in halting'
2022-03-06T06:17:10.958174+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/callbacks.rb:512:in `block in invoke_before'
2022-03-06T06:17:10.958175+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/callbacks.rb:512:in `each'
2022-03-06T06:17:10.958175+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/callbacks.rb:512:in `invoke_before'
2022-03-06T06:17:10.958176+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/callbacks.rb:115:in `block in run_callbacks'
2022-03-06T06:17:10.958176+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/callbacks.rb:137:in `run_callbacks'
2022-03-06T06:17:10.958177+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
2022-03-06T06:17:10.958178+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
2022-03-06T06:17:10.958178+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
2022-03-06T06:17:10.958178+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/notifications.rb:203:in `block in instrument'
2022-03-06T06:17:10.958179+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2022-03-06T06:17:10.958179+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/notifications.rb:203:in `instrument'
2022-03-06T06:17:10.958179+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
2022-03-06T06:17:10.958180+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
2022-03-06T06:17:10.958180+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activerecord (6.1.4.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
2022-03-06T06:17:10.958180+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/abstract_controller/base.rb:165:in `process'
2022-03-06T06:17:10.958181+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionview (6.1.4.4) lib/action_view/rendering.rb:39:in `process'
2022-03-06T06:17:10.958181+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_controller/metal.rb:190:in `dispatch'
2022-03-06T06:17:10.958181+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_controller/metal.rb:254:in `dispatch'
2022-03-06T06:17:10.958182+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
2022-03-06T06:17:10.958182+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
2022-03-06T06:17:10.958182+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
2022-03-06T06:17:10.958182+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/journey/router.rb:32:in `each'
2022-03-06T06:17:10.958186+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/journey/router.rb:32:in `serve'
2022-03-06T06:17:10.958186+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/routing/route_set.rb:842:in `call'
2022-03-06T06:17:10.958186+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
2022-03-06T06:17:10.958186+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] rack (2.2.3) lib/rack/etag.rb:27:in `call'
2022-03-06T06:17:10.958187+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
2022-03-06T06:17:10.958187+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] rack (2.2.3) lib/rack/head.rb:12:in `call'
2022-03-06T06:17:10.958187+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
2022-03-06T06:17:10.958187+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
2022-03-06T06:17:10.958187+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
2022-03-06T06:17:10.958188+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
2022-03-06T06:17:10.958188+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/cookies.rb:689:in `call'
2022-03-06T06:17:10.958188+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
2022-03-06T06:17:10.958188+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
2022-03-06T06:17:10.958189+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2022-03-06T06:17:10.958189+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
2022-03-06T06:17:10.958189+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
2022-03-06T06:17:10.958189+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
2022-03-06T06:17:10.958190+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
2022-03-06T06:17:10.958190+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
2022-03-06T06:17:10.958190+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
2022-03-06T06:17:10.958191+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
2022-03-06T06:17:10.958191+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
2022-03-06T06:17:10.958191+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
2022-03-06T06:17:10.958192+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
2022-03-06T06:17:10.958192+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
2022-03-06T06:17:10.958192+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
2022-03-06T06:17:10.958193+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
2022-03-06T06:17:10.958193+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
2022-03-06T06:17:10.958193+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2022-03-06T06:17:10.958194+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
2022-03-06T06:17:10.958194+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
2022-03-06T06:17:10.958194+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
2022-03-06T06:17:10.958195+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:113:in `call'
2022-03-06T06:17:10.958195+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
2022-03-06T06:17:10.958195+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] puma (5.5.2) lib/puma/configuration.rb:249:in `call'
2022-03-06T06:17:10.958195+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
2022-03-06T06:17:10.958196+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
2022-03-06T06:17:10.958199+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
2022-03-06T06:17:10.958199+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] puma (5.5.2) lib/puma/server.rb:447:in `process_client'
2022-03-06T06:17:10.958199+00:00 app[web.1]: [7e121cfc-bed1-4a2c-9367-5f77fb8f8b76] puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
2022-03-06T06:17:10.958993+00:00 heroku[router]: at=info method=POST path="/users" host=www.reptileslog.com request_id=7e121cfc-bed1-4a2c-9367-5f77fb8f8b76 fwd="61.198.85.174,172.70.233.95" dyno=web.1 connect=0ms service=11ms status=422 bytes=1896 protocol=http
```

**Comment by takyyk** [comment]
> HTTP Origin header (https://www.reptileslog.com) didn't match request.base_url (http://www.reptileslog.com)

と出ていますね！　httpsの接続周りでうまくいってなさそうです。

一度config/production.rbのSSL設定などを見直してみてください！

**Comment by shuhei-T** [comment]
@takyyk 
おっしゃるとおりでした。
元の`https://reptileslog.herokuapp.com/`
のURLからユーザー作成したら、なんの問題も無くできました。

SSL認証を見直してみます。

もしかしたら、先程質問させていただいた、サイトマップの件もSSL認証ができていない事が関係あるかもと思いました。

最後に一件聞きたいことがあるのですが、実はherokuの独自ドメイン化した際のSSL化なんですが、Cloudflareを使っています。
なぜかというとHerokuでSSL化すると月額7＄かかるので、調べるとCloudflareを使って無料でSSL化できる情報を見たからです。
https://qiita.com/healing_code/items/0e334606709fb9deae87

今回の不具合もそうですが、やはり独自ドメインのSSl化はHerokuに課金するべきなのでしょうか?

**Comment by takyyk** [comment]
いえ、特に独自ドメインのSSL化でHerokuに課金した方がいいというわけではないです！
CloudFlareを通している分のハマりポイントは増えるかもしれませんが、技術構成としてCloudflare + Herokuというのは問題ないかと思いますー！

**Comment by shuhei-T** [comment]
@takyyk 
Cloudflare側の設定を変えたら、うまくいきました！ありがとうございます!

**Comment by tam8** [comment]
こんにちは、はじめまして。

Heroku + Cloudflare SSLでdeviseの同じエラーが出ています(>_<)

Cloudflareでどんな設定をされたのか、アドバイスいただきたいです

**Comment by shuhei-T** [comment]
@tam8 
こんばんは！
一度下記の記事の通りやってみてほしいです！

https://osamudaira.com/461/

**Comment by tam8** [comment]
こんにちは。
どうも同じエラー文でも、色々パターンあるようで、ダメでした(>_<)
・出る人と出ない人がいる
・Heroku オリジナルのURLでも出る
など、まだ格闘が必要そうです
ありがとうございます！
